### ISSUE TITLE
Citing quadpy

### ISSUE THREAD

**Issue by utf** [sigma-py/quadpy#313]
Firstly, thank you for developing this package. I've found it exceptionally useful in my work.

Have you considered published a short manuscript on quadpy so that i) it can be referenced properly in an academic papers, and ii) you can receive appropriate recognition for the work you've put into the project.

If you haven't already looked into this, the [Journal of Open Source Software](https://joss.theoj.org) (JOSS) is a fantastic place to publish software articles. The papers are very short and generally only take 1-2 days to write. I think an article on quadpy would be well received.

**Comment by nschloe** [comment]
Sure. For now you can cite it by the doi given at the head of the readme.

**Comment by utf** [comment]
Thanks for the pointer to the zenodo repository.
