### ISSUE TITLE
orthopy and ndim missing in dependencies

### ISSUE THREAD

**Issue by jbund256** [sigma-py/quadpy#445]
Hello everyone, 

after installing the latest version of quadpy (version 0.16.11) with pip and running my code that uses quadpy, I get the following error:
`ModuleNotFoundError: No module named 'orthopy'`
After installing this module with pip, I get this error again but with the module ndim. 
With older versions of quady (I tested it with 0.16.10 and 0.16.9) I did not get these errors. 

Is it possible that these two modules (orthopy and ndim) are not listed in the dependencies?

**Comment by nschloe** [comment]
Those are listed as dependencies and I myself haven't had any problems yet. Does it work when manually installing orthopy and ndim?

**Comment by jbund256** [comment]
Yes. After i got those errors, I installed both modules manually and it worked. 

I tested it on new virtual environments, once with tox and once manually, on python versions 3.8 and 3.9.

**Comment by nschloe** [comment]
That's really weird. I cannot reproduce the issue, and I've tested it on several different machines.

**Comment by nschloe** [comment]
The deps were now _optional_. I've made them mandatory again now.
