### ISSUE TITLE
Quantum Packet Evolution integration - returning constant

### ISSUE THREAD

**Issue by REsteche** [sigma-py/quadpy#447]
Maybe I'm just too newbie to python yet and not realizing my own error, but the scrpit below is returning a constant value after integration, even though I know the expected result shouldn't be in that format

```python
from math import pi
import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft, ifft
import quadpy


i = 0 + 1j


p_0 = 1
delta = 5 
x_0 = -50 
m = 0.5
L = 1 
hbar = 1
k_0 = 1




def psi_init(x) :
    return 1/(2*pi*(delta)**2)**(0.25)*np.exp(-(x-x_0)**2/(4*delta**2))*np.exp(i*p_0*x/hbar)

vecpsi_i = np.vectorize(psi_init)


N = 150
x = np.arange(-75, 75, 10./(2*N))

cond_init = 1/(2*pi*(delta)**2)**(0.25)*np.exp(-(x-x_0)**2/(4*delta**2))*np.exp(i*p_0*x/hbar)

def phi(k) :
    return abs(fft(cond_init)) / np.sqrt(len (cond_init)) 
               
k = np.arange(-75, 75, 10./(2*N))
tempo = 40  

evolve = phi(k)*np.exp(i*hbar*tempo*(k**2)/(2*m))
psi_evolve = abs(fft(evolve)) / np.sqrt(len (evolve))


plt.plot(x, abs(vecpsi_i(x))**2, label='initial condition $|\psi(x,0)|^2$')
plt.plot(x, abs(psi_evolve)**2, label='$|\psi(x,t)|^2$ for $t>0$')
plt.legend() 
plt.grid()
plt.show()


prob_dens = abs(psi_evolve)**2 


def funpd(x):
    tam = x.astype(int)
    return prob_dens[tam]
funpd_vec = np.vectorize(funpd)


def V1(x) :
    return 2/((x - 1)*(x + 1/(1 + i*k_0)) + 1e-10) 
v1_vec = np.vectorize(V1)
 

def dNdt(x):
    return funpd(x)*V1(x) 
  
dndt_vec = np.vectorize(dNdt)


def plot(t):
    min = 0
    max = 1
    y,err = quadpy.quad(dNdt, min, max)
    return -y
plot_vec = np.vectorize(plot) 


T = np.arange(0, 1, 10./(2*N))
plt.plot(T, abs(plot_vec(T))**2)
plt.show()

```

the first graph tells me that everything is ok with the function generated by the fourier transforms, and its behavior is physically coherent

![image](https://user-images.githubusercontent.com/46388088/162974914-159821a0-6bd7-4ad6-9ead-926ca98fc41f.png)

however I don't understand why quadpy returns me a constant after integration at the end.

![image](https://user-images.githubusercontent.com/46388088/162975125-c008fea3-85f2-45c5-8855-2e05e1bdefad.png) 

I had some problems before modifying the code a bit as quadpy was saying that it was impossible to refine the precision of the integration, but after solving that, I came across this straight line and I don't know if it's my mistake or if I couldn't get around it the inaccuracy in an acceptable way only. 

Thanks in advance!

**Comment by nschloe** [comment]
>  if I need to improve something just let me know

Yes: Make it smaller. Ten lines max.

**Comment by REsteche** [comment]
Sorry, I think I didn't efficiently separate what was relevant information and what wasn't (to me everything seems relevant a priori)

What you think of

```python 
import numpy as np
import matplotlib.pyplot as plt
import quadpy

N = 150 ; i= 0 + 1j ; k_0 = 1
x = np.arange(-75, 75, 10./(2*N))

def V1(x) :
    return 2/((x - 1)*(x + 1/(1 + i*k_0)) + 1e-10) 

def plot(t):
    min = 0
    max = 1
    y,err = quadpy.quad(V1, min, max)
    return -y
plot_vec = np.vectorize(plot) 

T = np.arange(0, 1, 10./(2*N))
plt.plot(T, abs(plot_vec(T))**2)
plt.show()
```
Honestly, I think it's the best I can do. It's not even the code that caused the problem anymore, but it's something close to what I believe that initially started the confusion... hope it's enough for you.  

the problem that the library accuses is:
>> IntegrationError: Tolerances (abs: 1.49e-08, rel: 1.49e-08) could not be reached with the given max_num_subintervals (= 50).

**Comment by nschloe** [comment]
You don't need to plot. There's no need for `V1` to be that complicated. etc.

**Comment by REsteche** [comment]
> You don't need to plot. There's no need for `V1` to be that complicated. etc.

ok, but `V1` is the function that quadpy is having problems integrating, so if I change the function I have no guarantee that the problem will persist. I'll post the code without the plot, but I don't see how that drastically changes his size...

```python 
import numpy as np
import quadpy

N = 150 ; i= 0 + 1j ; k_0 = 1
x = np.arange(-75, 75, 10./(2*N))

def V1(x) :
    return 2/((x - 1)*(x + 1/(1 + i*k_0)) + 1e-10) 

def plot(t):
    y,err = quadpy.quad(V1, 0, 1)
    return -y
plot_vec = np.vectorize(plot) 
``` 

but anyway no problem, I'll try other approaches, going to leave the report here in case you're interested in following up

**Comment by nschloe** [comment]
> ok, but V1 is the function that quadpy is having problems integrating, so if I change the function I have no guarantee that the problem will persist.

Then you make simplifications as much as possible.

You also don't need `x`, `N` etc.

Also, please make clear what you expect from the integration, and what the actual result is. A `print()` statement helps.

**Comment by nschloe** [comment]
Okay, here's what an MWE looks like:

This:

```python
import quadpy


def V1(x):
    return 2 / ((x - 1) * (x + (1 - 1j) / 2) + 1e-10)


quadpy.quad(V1, 0.0, 1.0)
```
gives
```
quadpy.c1._adaptive.IntegrationError: Tolerances (abs: 1.49e-08, rel: 1.49e-08) could not be reached with the given max_num_subintervals (= 50).
```
Why?

**Comment by nschloe** [comment]
You'll notice that you get the same error for even simpler functions, like
```
def V1(x):
    return 1 / x
```
Why?

**Comment by REsteche** [comment]
> You'll notice that you get the same error for even simpler functions, like
> 
> ```python
> def V1(x):
>     return 1 / x
> ```
> 
> Why?

honestly, i don't know, but that's exactly what i would like to know

**Comment by nschloe** [comment]
Do you know what the _exact_ integral of `1/x` between 0 and 1 is?

**Comment by REsteche** [comment]
> Do you know what the _exact_ integral of `1/x` between 0 and 1 is?

Oooh nice! thanks for the tip, I wasn't considering the integration limits

**Comment by nschloe** [comment]
Yeah, poles almost always create problems. There are integrable poles, too, but other integration methods are more suitable here (tanh-sinh). Quadrature problem on non-integrable poles (like yours) are simply ill-defined.

As for creating MWEs: It's great that you started off with a complete example! (Not everyone does that.) In the future, you can do even better by making things more minimal. I'm convinced you could have reached the final one-liner (`quadpy.quad(lambda x: 1/x, 0, 1)`) yourself. The smaller the code, the easier the issue is to find.

Anyway, good luck with your research!

**Comment by REsteche** [comment]
Thanks for your attention during the working day hehe it was really helpful to find the problem. Next time I'll do my best to create the MWE in a more professional way.
