### ISSUE TITLE
Where's the code gone?

### ISSUE THREAD

**Issue by keithbriggs** [sigma-py/quadpy#450]
The repo seems to have only README.md :(

**Comment by nschloe** [comment]
I'm reorganizing my repos atm. The code should continue to work as before though.

**Comment by keithbriggs** [comment]
Ok, thanks.   I needed to install on a new machine, and pip failed and I could not download from the repo.   Any estimate of when it will be restored?

**Comment by nschloe** [comment]
I'm extremely busy right now, so it's hard to give estimates.

What's not working for you right now exactly?

**Comment by keithbriggs** [comment]
I can't install quadpy on a new machine.

pip install exits with a message about the orthopy dependency being missing.   And I have not kept a zip of the quadpy source, because normally I install with pip.
________________________________

**Comment by nschloe** [comment]
Please post what command you're running and what output you're getting.

**Comment by keithbriggs** [comment]
I can't do that exactly, as I am now in the middle of an OS version update on the machine.  It was something like...

pip install quadpy
Downloading...
[ok]
Downloading...
[ok]
Cannot satisfy orthopy dependency <0.10 >0.9.

________________________________

**Comment by nschloe** [comment]
What do you get on
```
pip install orthopy -v
```
?

**Comment by keithbriggs** [comment]
I will tell you when my OS upgrade finishes.
________________________________

**Comment by Jajiko** [comment]
Sorry if this is unrelated, but to me it seems to be. 

Before yesterday,  I could install orthopy==0.9.6 from PyPi. Now, according to https://pypi.org/project/orthopy/, the latest version is 0.8.91. So apparently 0.9.x has just disappeared?

**Comment by nschloe** [comment]
@Jajiko When trying to retroactively fix a version, I accidentally deleted the 0.9* versions. It doesn't matter much though since the 0.9* series wasn't just for playing around, and I noticed afterwards that it's public. If it worked for you, so will 0.8.*.

**Comment by keithbriggs** [comment]
Should that be "was just for playing around"?

**Comment by nschloe** [comment]
Indeed, fixed.
