### ISSUE TITLE
Code gone, unable to install via pip

### ISSUE THREAD

**Issue by denizokt** [sigma-py/quadpy#451]
Hi, it seems like the code is gone. According to closed issues, the pip install should be working, but I am running into issues.

`pip install quadpy`
gives me
`ERROR: Could not find a version that satisfies the requirement quadpy (from versions: none)
ERROR: No matching distribution found for quadpy`
I am using Python 3.6.8 (I am unfortunately stuck with this version)

**Comment by nschloe** [comment]
Python 3.6 has been unsupported for a number of years now. It's even unsupported by upstream Python since last year. It's theoretically possible to bring it back, but it'd be _so_ much work for me that I don't think it'd be worth it.
