### ISSUE TITLE
Error Installing Quadpy

### ISSUE THREAD

**Issue by Filippo221** [sigma-py/quadpy#452]
Hi everyone,

I am trying to install quadpy in my virtual environment. However, when I input >>>pip3 install quadpy, I get the following error message:
ERROR: Could not find a version that satisfies the requirement x21>=0.2.6 (from quadpy) (from versions: 0.0.1)
ERROR: No matching distribution found for x21>=0.2.6

I have already tried installing x21 with pip (version 0.0.1) and upgrading it to the latest version (0.2.6). However, it has not solved the issue. 
Edit: I have also downloaded the wheel x21-0.2.6-cp38-cp38-macosx_10_9_x86_64.whl, which to my understanding should be the correct one for my MacBook 14inches with python3.8.9 running in the virtual environment. However, when I try to build it with pip3 install x21-0.2.6-cp38-cp38-macosx_10_9_x86_64.whl, I get the following error:
ERROR: x21-0.2.6-cp38-cp38-macosx_10_9_x86_64.whl is not a supported wheel on this platform.

Does anyone know how to fix this?

Thank you

Best

**Comment by nschloe** [comment]
What's your Python version?

**Comment by Filippo221** [comment]
Thank you for the prompt reply

My python version running in the environment is 3.8.9. I have updated my thread with some further developments

**Comment by nschloe** [comment]
What's your machine architecture?

**Comment by Filippo221** [comment]
ARM

**Comment by nschloe** [comment]
I see. I'll check it out in the weekend.

**Comment by Filippo221** [comment]
Thank you I really appreciate it

Keep my posted

**Comment by nschloe** [comment]
Okay, you can try again.

**Comment by Filippo221** [comment]
Now I can install the package. However, when I try to import it, I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../python_env/lib/python3.8/site-packages/quadpy/__init__.py", line 1, in <module> from x21 import __dex__
ImportError: dlopen(/Users/fg/UCSCIPHYL2/python_env/lib/python3.8/site-packages/x21.cpython-38-darwin.so, 0x0002): tried: '/Users/.../python_env/lib/python3.8/site-packages/x21.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/x21.cpython-38-darwin.so' (no such file), '/usr/lib/x21.cpython-38-darwin.so' (no such file)

Once I get back home, I will try to use the package on a older MacBook (2014) to see if the issue only presents itself with ARM MacBooks. 

Thank you for your patience

**Comment by nschloe** [comment]
What pip version are you running?

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
