### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by jbund256** [sigma-py/quadpy#453]
Hello, 

I was wondering what the license of this project is. Earlier versions (before 0.16.10 I think) were licensed under a GPL license. 
For the recent versions (especially 0.16.15 and 0.16.16) that are available via pip, I cannot find a proper license information. 
Did I just miss the place where it is specified?
Thanks in advance.

**Comment by jbund256** [comment]
Does that mean that the project has currently no license? In that case the code is not save to use, right?
 
```Until then, everything should continue to work as normal.```
Do you mean by that, that the ealier license (GPL) is still valid?

**Comment by nschloe** [comment]
> Do you mean by that, that the ealier license (GPL) is still valid?

No, quadpy is no longer distributed under the GPL. I haven't decided yet under what license exactly it will be distributed in the future. If you feel uncomfortable here (which I completely understand), I would recommend not using it for now.
