### ISSUE TITLE
Quadpy usage

### ISSUE THREAD

**Issue by RusMermaid** [sigma-py/quadpy#458]
### Discussed in https://github.com/sigma-py/quadpy/discussions/457

<div type='discussions-op-text'>

<sup>Originally posted by **RusMermaid** October 10, 2022</sup>
Hi, can you share the sourse code so I can tranlate it to C#. I am building a c# complex math library so this would help too. Thanks!</div>

**Comment by nschloe** [comment]
Maybe later.
