### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by keithbriggs** [sigma-py/quadpy#464]
```
kbriggs> python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from quadpy import u3
Warning: Unable to find valid license in
- environment variable SIGMA_LICENSE_KEY (env var not found), or
- config file /home/kbriggs/.local/share/sigma/sigma.toml (file not found)

Enter new license key for sigma: foo

Error: Invalid sigma license (product ID mismatch).
```

**Comment by keithbriggs** [comment]
This downgrade fixed it for me:

`python3 -m pip install --force-reinstall -v "x21==0.3.6"`

**Comment by minsungk** [comment]
I got the same issue, but the downgrade doesn't work on my side.

```
Python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
fr>>> from quadpy import u3
Warning: Unable to find valid license in
- environment variable SIGMA_LICENSE_KEY (env var not found), or
- config file /u/minsungk/.local/share/sigma/sigma.toml (file not found)
```

**Comment by bastonero** [comment]
Dear developers,
I had the same issue; was not able to fix with the suggested downgrade. Any help is appriciated.

**Comment by nschloe** [comment]
I'll have some time to look at the problem later today.

**Comment by mbarbattini** [comment]
@nschloe Was the problem with the x21 module? I saw that it was updated on 1/16/23 but quadpy itself has not been updated since your comment. Anyway using the new version of x21 0.4.1 did not solve this issue.

**Comment by fdedo** [comment]
Hi, sorry to bother but I didn't get how you fixed it. I tried the downgrade but didn't work. Any further help?

**Comment by nschloe** [comment]
@fdedo This issue is fixed in the latest revision. If you have any more problems, just mail me at nico.schloemer@gmail.com with more details.
