### ISSUE TITLE
Importing quadpy causes python to quit without any error message

### ISSUE THREAD

**Issue by keithbriggs** [sigma-py/quadpy#469]
This is with quadpy-0.16.22:
```
kbriggs:~> python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import quadpy
kbriggs:~> 
```

**Comment by nschloe** [comment]
Really? Damn, I messed it up. Let me look into it. I hope I won't mess up the release process one day... :confounded:

**Comment by nschloe** [comment]
Ah wait, maybe you haven't updated ndim/orthopy?

**Comment by keithbriggs** [comment]
That seems to fix it!  Why aren't ndim and orthopy listed as dependencies, so that pip upgrades them automatically?

**Comment by nschloe** [comment]
Good point, another shortcoming of the process. I'm hoping to fix all these things for good in the next few weeks.
