### ISSUE TITLE
Issue upgrading quadpy

### ISSUE THREAD

**Issue by afcorral-desy** [sigma-py/quadpy#470]
Today I tried running a program that yesterday was working. 
I found the common message of outdated library:
"This version of quadpy is outdated. Please upgrade."

I did install the latest version (quadpy==0.16.24) and also did the same for orthopy and ndim.

However, when I ran my program, I get an error on the command import quadpy, that has to do with some dictionary that is not found:

'FileNotFoundError: [Errno 2] No such file or directory: '/home/.../lib/python3.8/site-packages/quadpy/_agg/t2_dunavant_05.json'

**Comment by nschloe** [comment]
Ah interesting. Did you just import quadpy, or what command did you run?

**Comment by nschloe** [comment]
Ah wait yeah, I see what's missing. Let me fix...

**Comment by afcorral-desy** [comment]
Yes, it was importing quadpy. Former error is no longer there but now I am seeing that with quadpy 0.16.25, there is still this error:

ImportError: cannot import name '_eXxZr' from 'quadpy._agg' (/home/...lib/python3.8/site-packages/quadpy/_agg/__init__.py)

Thanks for the fast response

**Comment by nschloe** [comment]
That was an accidental upload, try 0.16.26.

**Comment by afcorral-desy** [comment]
Everything working now. Thanks :)

**Comment by nschloe** [comment]
Cool. If you you run into any more issues, let me know.
