### ISSUE TITLE
Unable to find valid license for Sigma. 

### ISSUE THREAD

**Issue by yujie4phy** [sigma-py/quadpy#471]
I am trying to run my program today that was working few weeks ago. 

The error message I found (After upgrading quadpy/orthopy ) was

"Error: Unable to find valid license for Sigma. 
Add a license with
    plm add <your-license-key>"

Before upgrading orthopy:  the error goes:  "orography version no longer support".

I have also tried to uninstalled everything and reinstalled everything (Maybe not properly enough?). It would be really helpful if you have any thought on how to fixed that.

**Comment by nschloe** [comment]
Hi,

Thanks for the message! You can find instructions on how to get a quadpy license [here](https://github.com/sigma-py). You just need one license to run all of quadpy, orthopy etc.

**Comment by yujie4phy** [comment]
> Hi,
> 
> Thanks for the message! You can find instructions on how to get a quadpy license [here](https://github.com/sigma-py). You just need one license to run all of quadpy, orthopy etc.

Thanks for your prompt response,  I am wondering, is this requirement for quadpy license new? Since my program was able to be run without a license previously, I am only using a spherical integration function associated with it in my code.

**Comment by nschloe** [comment]
> Thanks for your prompt response, I am wondering, is this requirement for quadpy license new? 

Yeah, it's new! I've had quadpy issue warnings about the upcoming change for about 3 months now though. Does this break your workflow right now? Best write support@mondaytech.com for a quick solution.
