### ISSUE TITLE
Sigma license for quadpy

### ISSUE THREAD

**Issue by TryoenJ** [sigma-py/quadpy#479]
Hello Nico.

Il would like to use quadpy for NVIDIA Modulus. However it seems that I need a Sigma license to use it.

Could you please confirm me this information? If yes, is there an old version of quadpy which don't need this license? It is a problem for me because NIVIDIA Modulus relies on it for some applications.

If I have no choice, I think I will get a license. I will need in that case an expense account. Could you please tell me how to get it.

Thanks for your answer.

Julie

**Comment by nschloe** [comment]
Hi, best write support@mondaytech.com.
